msgBuf: 16 #消息缓冲区大小
logLevel: "Debug" #日志级别：Trace,Debug,Info,Warn,Error

bili:
  # b站开播提醒，内容为用户的b站uid
  live:
    - 672342685
  # b站动态更新提醒
  dynamic:
    - 703007996

# 抖音开播提醒
tiktok:
  # 网页端cookies 中的 “__ac_nonce”
  nonce: ""
  # 网页端cookies 中的 "__ac_signature"
  signature: ""
  # 网页端的直播间号
  users:
    - "804284713107"

# 推送到钉钉群机器人
dingTalk:
  webhook: ""
  secret: ""

# 通过cqhttp推送到qq频道
cqBot:
  host: ""
  token: ""
  bufSize: 16