msgBuf: 16 #消息缓冲区大小
logLevel: "Debug" #日志级别：Trace,Debug,Info,Warn,Error

bili:
  # roomId，房间号
  live:
    - 22625027
    - 22632424

  # uid
  dynamic:
    - 672342685
    - 672353429

tiktok:
  # 网页端cookies 中的 “__ac_nonce”
  nonce: ""
  # 网页端cookies 中的 "__ac_signature"
  signature: ""
  # 网页端的直播间号
  users:
    - "804284713107"

dingTalk:
  webhook: ""
  secret: ""

cqBot:
  host: ""
  token: ""
  bufSize: 16